@startuml
skinparam classAttributeIconSize 0
skinparam groupInheritance 2
left to right direction

class Project {
    - name: String
    - description: String
    - technologies: List<String>
}

class Persona {
    - id: UUID
    - jobTitle: String
    - skills: List<String>
    - certificates: List<String>
    - projectHistory: List<Project>
    - startingDate: Date
    - lastUpdate: Date
    + saveVita()
    + updateVita()
}
package root <<Folder>>{

  package vita <<Folder>>{
      package uuid <<Folder>>{
          note as n
            persona.yml
            project1.yml
            project2.yml
            project3.yml
          end note
      }
  }

  package bids <<Folder>>{
  }
}

root.vita.uuid.n -- Persona::saveVita
root.vita.uuid.n -- Persona::updateVita
Persona::projectHistory *-- Project
@enduml