@startfiles
/src/test/resources/personas/jennifer_jansen/persona.json
/src/test/resources/personas/jennifer_jansen/information.md
/src/test/resources/personas/juergen_peter/persona.json
/src/test/resources/personas/juergen_peter/information.md
@endfiles
