[plantuml,format=png]
----
!pragma layout smetana
@startuml
participant "Alice" as participant_alice
participant "Bob" as participant_bob

[-> participant_alice : recieves external stimulus
activate participant_alice

participant_alice -> participant_bob : asks for help
activate participant_bob
note right
    Bob is a helpful guy :-)
end note

participant_bob -> participant_alice : gives advice
deactivate participant_bob

participant_alice -> participant_alice : considers advice

[<- participant_alice : responds to extenal stimulus

@enduml
----